services:
  fastapi_learn:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_learn:v1
    container_name: fastapi_learn
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-false}
    # volumes:
    #   - ./fastapi_learn:/app
    restart: unless-stopped
    networks:
      - app-network

  fastapi_nginx:
    image: nginx:alpine
    container_name: fastapi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - fastapi_learn
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
