services:
  django_learn:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_learn:v1
    container_name: django_learn
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG:-false}
    # volumes:
    #   - ./django_learn:/app
    restart: unless-stopped
    networks:
      - app-network

  django_nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - django_learn
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
